import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import React from 'react'
import SearchBar from '../components/SearchBar'
import MainDestinetions from '../components/MainDestinetions'
import PropertyType from '../components/PropertyType'
import Guests from '../components/Guests'
import Email from '../components/Email'
import Footer from '../components/Footer'
import {axiosReq} from '../util/apiCalls'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>JerBooking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.main}>
        <SearchBar />
        <MainDestinetions />
        <PropertyType />
        <Guests />
      </div>
      <Email />
      <Footer />
      
    </div>
  )
}
export async function getServerSideProps(context) {
  const {data} = await axiosReq.get('hotels')
  return {
    props: {data}, // will be passed to the page component as props
  }
}