import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/List.module.css'
import React, { useEffect, useState } from 'react'
import SearchItem from '../components/SearchItem'
import { useRouter } from 'next/router'
import {axiosReq} from '../util/apiCalls'
import { format } from 'date-fns';

export default function List() {
  const router = useRouter()
  const {startDate, endDate, destination} = router.query
  const [hotels, setHotels] = useState([])
  const [newDestination, setNewDestination] = useState(destination)
  const [newStartDate, setNewStartDate] = useState(startDate)
  const [newEndDate, setNewEndDate] = useState(endDate)

  useEffect(() => {
      const getHotels = async () => {
        try {
          const res = await axiosReq.get(`hotels?city=${destination}`)
          setHotels(res.data)
          console.log(res.data);
        } catch (error) {
          console.log(error);
        }
      }
      getHotels()
  }, [])
  
  const handleSubmit = async () => {
    try {
      const res = await axiosReq.get(`hotels?city=${newDestination}`)
      setHotels(res.data)
      console.log(hotels);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>JerBooking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.searchContainer}>
          <div className={styles.wrapper}>
              <div className={styles.search}>
                <h1>Search</h1>
                <div className={styles.input}>
                    <label htmlFor="destination">Destination</label>
                    <input type="text" name="destination" id="destination" placeholder={destination} value={newDestination} onChange={(e) => setNewDestination(e.target.value)} />
                </div>
                <div className={styles.input}>
                    <label htmlFor="date">Check-in date</label>
                    <input type="text" name="date" id="date" placeholder='04/27/2022 to 04/29/2022' />
                </div>
                <div className={styles.options}>
                    <span>Options</span>
                    <div className={styles.option}>
                        <span>Min price (per night)</span>
                        <input type="number" name="" id="" />
                    </div>
                    <div className={styles.option}>
                        <span>Min price (per night)</span>
                        <input type="number" name="" id="" />
                    </div>
                    <div className={styles.option}>
                        <span>Adult</span>
                        <input type="number" name="" id="" placeholder='2' />
                    </div>
                    <div className={styles.option}>
                        <span>Children</span>
                        <input type="number" name="" id="" placeholder='1' />
                    </div>
                    <div className={styles.option}>
                        <span>Room</span>
                        <input type="number" name="" id="" placeholder='2' />
                    </div>
                </div>
                <button onClick={handleSubmit}>Search</button>
              </div>
              <div className={styles.result}>
                    {hotels.length > 0 && hotels.map((hotel) => (
                      <SearchItem hotel={hotel} key={hotel._id} />
                    ))}
              </div>
          </div>
      </div>
    </div>
  )
}
